// Auto-generated Brazilian Portuguese word lists.
//
// Gameplay runs on accent-stripped keys (plain a-z), exactly like TERMO: you
// type without accents and letters match without them. DISPLAY maps a key to
// its proper accented spelling, which is what the board actually shows.

export const ANSWERS = [
  "abade", "abate", "abram", "abrem", "abria", "abril", "abrir", "abriu", "abuso", "acaba", "acabe", "acabo",
  "acaso", "acene", "acesa", "aceso", "acham", "achar", "achas", "achei", "achem", "achou", "acido", "acima",
  "acoes", "acusa", "adaga", "adega", "adeus", "adiar", "adora", "adore", "adoro", "aerea", "aereo", "afeta",
  "afeto", "afora", "agido", "agita", "agora", "aguas", "aguda", "agudo", "aguia", "ainda", "aires", "ajuda",
  "ajude", "ajudo", "album", "alega", "alema", "algas", "algum", "alias", "alibi", "almas", "altar", "altas",
  "altos", "aluga", "aluna", "aluno", "alvos", "amada", "amado", "amara", "amava", "ambar", "ambas", "ambos",
  "amiga", "amigo", "amora", "ampla", "amplo", "andam", "andar", "andei", "andem", "andou", "andre", "aneis",
  "anexo", "anima", "anime", "animo", "anjos", "anoes", "anote", "antes", "anual", "anzol", "aonde", "aorta",
  "apaga", "apelo", "apice", "apito", "apoia", "apoio", "apolo", "arabe", "arame", "arcar", "arcos", "arder",
  "arduo", "areas", "areia", "arena", "armar", "armas", "armou", "aroma", "arpao", "arroz", "artes", "artur",
  "asilo", "aspas", "assar", "assim", "astro", "ataca", "atira", "atire", "atiro", "ativa", "ative", "ativo",
  "atlas", "atomo", "atrai", "atras", "atriz", "atual", "atuar", "atuou", "aulas", "autor", "aveia", "aviao",
  "avisa", "avise", "aviso", "azedo", "azuis", "babar", "babas", "bacia", "baile", "baita", "baixa", "baixe",
  "baixo", "balao", "balas", "balde", "balsa", "bamba", "bambu", "banal", "banca", "banco", "banda", "bando",
  "banha", "banho", "banir", "banjo", "barao", "barba", "barca", "barco", "bares", "barra", "barro", "bases",
  "basta", "batam", "batem", "bater", "bates", "bateu", "batia", "batom", "bazar", "bebam", "bebem", "beber",
  "bebes", "bebeu", "bebia", "becos", "beija", "beije", "beijo", "beira", "belas", "belga", "belos", "benta",
  "berco", "besta", "bicha", "bicho", "bicos", "bingo", "bispo", "blefe", "bloco", "blusa", "boate", "boato",
  "bobas", "bobos", "bocas", "bodas", "bolar", "bolas", "bolha", "bolos", "bolsa", "bolso", "bomba", "bonde",
  "bonus", "borda", "bordo", "bosta", "botao", "botar", "botas", "botei", "botes", "botou", "braco", "brasa",
  "brava", "bravo", "breve", "briga", "brisa", "broca", "bruta", "bruto", "bruxa", "bruxo", "bunda", "burra",
  "burro", "busca", "busco", "busto", "cabem", "caber", "cabos", "cabra", "cacam", "cacar", "cacas", "cacos",
  "cafes", "cagar", "cagou", "caiam", "caida", "caido", "caira", "cairo", "caixa", "calar", "calca", "calda",
  "caldo", "calem", "calma", "calmo", "calor", "camas", "campo", "canal", "canoa", "canos", "cansa", "canso",
  "canta", "cante", "canto", "capas", "capaz", "capuz", "caras", "carga", "cargo", "carne", "caros", "carro",
  "carta", "casal", "casam", "casar", "casas", "casca", "casco", "casei", "casos", "casou", "casta", "catar",
  "cauda", "causa", "cause", "cavar", "cavou", "ceder", "cedeu", "cegas", "cegos", "celas", "cenas", "cento",
  "cerca", "cerco", "certa", "certo", "cervo", "cesar", "cesta", "cesto", "cetro", "chale", "chama", "chame",
  "chamo", "chapa", "chata", "chato", "chave", "checa", "chefe", "chega", "chego", "cheia", "cheio", "chico",
  "china", "chora", "chore", "choro", "chove", "chupa", "chupe", "chuta", "chute", "chuva", "ciclo", "cinco",
  "cinta", "cinto", "cinza", "circo", "cisco", "cisne", "citar", "citou", "ciume", "civil", "civis", "clara",
  "claro", "clima", "clone", "cloro", "clube", "cobra", "cobre", "cobri", "cobro", "cocar", "cocos", "cofre",
  "coisa", "colar", "colon", "colou", "comam", "comem", "comer", "comes", "comeu", "comia", "comum", "conde",
  "conta", "conte", "conto", "copas", "copia", "copos", "coral", "corda", "cores", "corno", "coroa", "corpo",
  "corra", "corre", "corri", "corro", "corta", "corte", "corto", "corvo", "cosmo", "cospe", "costa", "couro",
  "couve", "covas", "coxas", "credo", "creia", "creio", "creme", "criam", "criar", "crias", "criei", "crime",
  "criou", "crise", "cruel", "cruza", "cruze", "cubos", "cubra", "cubro", "cueca", "cuida", "cuide", "cuido",
  "cujas", "cujos", "culpa", "culpe", "culpo", "culto", "cupom", "curar", "curou", "curso", "curta", "curte",
  "curto", "curva", "cuspa", "custa", "custe", "custo", "dadas", "dados", "damas", "damos", "danar", "danca",
  "dance", "danco", "dando", "danem", "danos", "dante", "daqui", "darao", "dardo", "darei", "darem", "daria",
  "datas", "davam", "debil", "dedao", "dedos", "deita", "deite", "deixa", "deixe", "deixo", "delas", "deles",
  "delta", "demos", "densa", "denso", "dente", "depor", "deram", "derem", "desca", "desce", "desci", "desco",
  "desde", "dessa", "desse", "desta", "deste", "detem", "deter", "deusa", "devam", "devem", "dever", "deves",
  "devia", "diabo", "dicas", "dieta", "digam", "digas", "digna", "digno", "dirao", "direi", "diria", "disco",
  "disse", "disso", "disto", "ditar", "ditas", "dizem", "dizer", "dizes", "dizia", "dobra", "dobre", "dobro",
  "docas", "doida", "doido", "dolar", "domar", "donas", "donos", "dores", "dorme", "dormi", "doses", "drama",
  "droga", "ducha", "duelo", "dueto", "dunas", "dupla", "duplo", "duque", "duram", "durar", "duras", "durma",
  "durmo", "duros", "durou", "duzia", "egito", "eixos", "eleva", "elite", "emite", "encha", "enche", "enchi",
  "enfia", "enfie", "enfim", "enoja", "entao", "entes", "entra", "entre", "entro", "envia", "envie", "envio",
  "epica", "epico", "epoca", "errar", "errei", "erros", "errou", "ervas", "espia", "esqui", "essas", "esses",
  "estao", "estar", "estas", "estes", "estou", "etapa", "etica", "etico", "evita", "evite", "exame", "exata",
  "exato", "exige", "exijo", "exito", "expor", "expos", "extra", "facam", "facao", "facas", "faces", "facil",
  "fadas", "faixa", "falam", "falar", "falas", "falei", "falem", "falha", "falir", "falou", "falsa", "falso",
  "falta", "farao", "farda", "fardo", "farei", "faria", "farol", "farra", "farsa", "farta", "farto", "fases",
  "fatal", "fatia", "fator", "fatos", "favor", "fazem", "fazer", "fazes", "fazia", "febre", "fecha", "feche",
  "fecho", "fedem", "feder", "fedor", "feias", "feios", "feira", "feita", "feito", "feixe", "felix", "feliz",
  "femea", "femur", "fenda", "feras", "ferir", "feriu", "feroz", "ferra", "ferro", "festa", "fezes", "fibra",
  "ficam", "ficar", "ficas", "ficha", "ficou", "fieis", "filas", "filha", "filho", "filma", "filme", "final",
  "finas", "finge", "fingi", "finja", "finjo", "finos", "fique", "firma", "firme", "fitas", "fixar", "fizer",
  "flora", "fluir", "fluxo", "fobia", "focar", "focas", "fofos", "fogao", "fogem", "fogos", "folga", "folha",
  "fomos", "fones", "fonte", "foque", "foram", "forca", "force", "forem", "forma", "forno", "forro", "forte",
  "forum", "fossa", "fosse", "fosso", "foste", "fotos", "fraca", "fraco", "frase", "freio", "frias", "frios",
  "frita", "frito", "frota", "fruta", "fruto", "fugia", "fugir", "fugiu", "fujam", "fumar", "fumei", "fumou",
  "fundo", "fungo", "furar", "furia", "furos", "furou", "furto", "fusao", "futil", "fuzil", "gabar", "gaita",
  "galao", "galho", "galos", "gamba", "ganha", "ganhe", "ganho", "ganso", "garfo", "garra", "gases", "gasta",
  "gaste", "gasto", "gatas", "gatos", "gemea", "gemeo", "genes", "genio", "genro", "gente", "geral", "gerar",
  "gerir", "gerou", "gesso", "gesto", "girar", "globo", "gnomo", "golfo", "golpe", "gongo", "gorda", "gordo",
  "gorro", "gosma", "gosta", "goste", "gosto", "gotas", "gozar", "graca", "grade", "grama", "grana", "graos",
  "grata", "grato", "graus", "grava", "grave", "graxa", "grega", "grego", "greve", "grilo", "gripe", "grita",
  "grite", "grito", "grupo", "gruta", "gueto", "guiar", "guias", "guiou", "habil", "harem", "harpa", "haver",
  "havia", "helio", "heroi", "hindu", "homem", "honra", "horas", "horta", "hotel", "houve", "humor", "hurra",
  "iamos", "icone", "idade", "ideal", "ideia", "idolo", "idosa", "idoso", "ienes", "igual", "ileso", "ilhas",
  "imita", "impor", "imune", "india", "indio", "inves", "irado", "iriam", "irmao", "irmas", "irmos", "iscas",
  "janta", "japao", "jarra", "jarro", "jatos", "jaula", "jeito", "jejum", "jesus", "joana", "jogam", "jogar",
  "jogos", "jogou", "jogue", "joias", "jorge", "jovem", "judas", "judeu", "judia", "juiza", "juizo", "julga",
  "julgo", "julho", "junho", "junta", "junte", "junto", "jurar", "jurei", "juros", "jurou", "justa", "justo",
  "labio", "lacos", "lados", "ladra", "lagoa", "lagos", "lambe", "lanca", "lance", "lapis", "lapso", "lares",
  "larga", "largo", "larva", "laser", "latas", "latex", "latim", "latir", "lavar", "lavei", "lavou", "lazer",
  "leais", "lebre", "legal", "leiam", "leite", "leito", "lemos", "lenco", "lenda", "lendo", "lenha", "lenta",
  "lente", "lento", "leoes", "leram", "lerei", "lesao", "lesma", "lesse", "leste", "letra", "levam", "levar",
  "levei", "levem", "leves", "levou", "libra", "licao", "liceu", "licor", "lidam", "lidar", "lidei", "lider",
  "lidos", "lidou", "ligam", "ligar", "ligas", "ligou", "ligue", "limao", "limbo", "limpa", "limpe", "limpo",
  "linda", "lindo", "linha", "linho", "liras", "lista", "litro", "livra", "livre", "livro", "lixao", "lobos",
  "local", "locao", "loira", "loiro", "lojas", "lombo", "longa", "longe", "longo", "lorde", "lotes", "lotus",
  "louca", "louco", "loura", "louro", "lucas", "lucro", "lugar", "lunar", "lutam", "lutar", "lutas", "lutei",
  "lutem", "lutou", "luvas", "luzes", "macas", "macho", "macia", "macio", "mafia", "magia", "magoa", "magos",
  "magra", "magro", "maias", "maior", "major", "malas", "males", "malha", "malta", "mamae", "mamas", "manco",
  "manda", "mande", "mando", "manga", "manha", "mania", "manos", "manta", "manto", "mapas", "marca", "marco",
  "mares", "maria", "mario", "marta", "massa", "matam", "matar", "matei", "matem", "matou", "mecha", "media",
  "medio", "medir", "medos", "meias", "meiga", "meigo", "meios", "melao", "menor", "menos", "menta", "mente",
  "menti", "merce", "merda", "meros", "mesas", "meses", "mesma", "mesmo", "metal", "metas", "meter", "meteu",
  "metro", "mexam", "mexem", "mexer", "mexeu", "mexia", "micro", "midia", "mijar", "mijou", "milha", "milho",
  "minas", "minha", "minta", "minto", "mirar", "missa", "mitos", "miuda", "miudo", "mocao", "mocas", "modos",
  "moeda", "molde", "moles", "molho", "monge", "monta", "monte", "moral", "moram", "morar", "morda", "morde",
  "mordo", "morei", "morna", "morno", "morou", "morra", "morre", "morri", "morro", "morse", "morta", "morte",
  "morto", "mosca", "motel", "motor", "motos", "movam", "movel", "movem", "mover", "moveu", "movia", "mudam",
  "mudar", "mudei", "mudem", "mudou", "muita", "muito", "mulas", "multa", "mumia", "mundo", "mural", "muros",
  "murro", "museu", "musgo", "mutua", "mutuo", "nacao", "nadar", "nariz", "nasal", "nasce", "nasci", "natal",
  "naval", "naves", "navio", "negao", "negar", "negou", "negra", "negro", "negue", "nelas", "neles", "nenem",
  "nervo", "nessa", "nesse", "nesta", "neste", "netos", "nevar", "nevoa", "ninar", "ninho", "nisso", "nisto",
  "nivel", "nobre", "nocao", "noite", "noiva", "noivo", "nomes", "norma", "norte", "nossa", "nosso", "notar",
  "notas", "notei", "notou", "novas", "novos", "nozes", "nudez", "nunca", "nuvem", "oasis", "obito", "obras",
  "obtem", "obter", "obvia", "obvio", "ocupa", "odeia", "odeie", "odeio", "odiar", "odiei", "odiou", "oeste",
  "ogiva", "olham", "olhar", "olhei", "olhem", "olhos", "olhou", "ombro", "omega", "ondas", "ontem", "opcao",
  "opera", "optar", "ordem", "orfao", "orgao", "orgia", "ossea", "ossos", "ostra", "otica", "otima", "otimo",
  "oucam", "ousam", "ousar", "ousou", "outra", "outro", "ouvem", "ouvia", "ouvir", "ouviu", "ovulo", "oxala",
  "pacto", "padre", "pagam", "pagao", "pagar", "pagas", "pagos", "pagou", "pague", "palco", "palha", "palma",
  "panda", "panos", "papai", "papel", "param", "parar", "parei", "parem", "pareo", "pares", "paris", "pariu",
  "parou", "parta", "parte", "parti", "parto", "passa", "passe", "passo", "pasta", "pasto", "patas", "patio",
  "patos", "paula", "paulo", "pausa", "pavao", "pavio", "pavor", "pazes", "pecam", "pecas", "pedal", "pedem",
  "pedia", "pedir", "pediu", "pedra", "pedro", "pegam", "pegar", "pegas", "pegou", "pegue", "peido", "peito",
  "peixe", "pelas", "peles", "pelos", "penal", "penas", "penis", "pensa", "pense", "penso", "pente", "peoes",
  "perca", "perco", "perda", "perde", "perdi", "perna", "persa", "perto", "perua", "perus", "pesar", "pesca",
  "pesos", "peste", "piada", "piano", "picar", "picos", "pilar", "pilha", "pinca", "pingo", "pinos", "pinta",
  "pinte", "pinto", "piora", "piore", "pisar", "pisca", "pisei", "pisou", "pista", "pizza", "placa", "plana",
  "plano", "plena", "pleno", "pneus", "pobre", "pocao", "pocos", "podem", "poder", "podes", "podia", "poema",
  "poeta", "polar", "polir", "polvo", "pomar", "pomba", "pombo", "pondo", "ponei", "ponha", "ponho", "ponta",
  "ponte", "ponto", "porao", "porca", "porco", "porei", "porem", "poria", "poros", "porra", "porre", "porta",
  "porte", "porto", "posar", "possa", "posse", "posso", "posta", "poste", "posto", "potes", "potro", "pouca",
  "pouco", "poupa", "poupe", "pouso", "povos", "praca", "prado", "praga", "praia", "prata", "prato", "prazo",
  "prece", "preco", "prega", "prego", "presa", "preso", "preta", "preto", "preve", "previ", "prima", "prime",
  "primo", "prole", "prova", "prove", "puder", "pudim", "pular", "pulei", "pulou", "pulso", "punho", "punir",
  "puros", "puser", "putas", "putos", "puxar", "puxei", "puxem", "puxou", "quais", "quase", "queda", "quero",
  "quilo", "rabos", "racao", "racas", "radar", "radio", "raios", "raiva", "ramos", "rampa", "range", "rapaz",
  "rapto", "raras", "raros", "ratos", "razao", "reais", "recem", "recue", "redes", "redor", "reduz", "refem",
  "regra", "reina", "reino", "relva", "remar", "remem", "remos", "renal", "renas", "renda", "rende", "rendo",
  "repor", "resta", "resto", "reter", "reuna", "reune", "rever", "rezar", "rezei", "ricas", "ricos", "rifle",
  "rigor", "rimas", "rimos", "rindo", "riram", "rirem", "risco", "risos", "ritmo", "rival", "robos", "rocha",
  "rodar", "rodas", "rolar", "rolha", "rolos", "rolou", "ronca", "ronco", "ronda", "rosas", "rosto", "rotas",
  "rouba", "roube", "roubo", "roupa", "rudes", "rugas", "ruido", "ruina", "ruins", "ruiva", "ruivo", "rumor",
  "rural", "russa", "russo", "saara", "sabao", "sabem", "saber", "sabes", "sabia", "sabio", "sabor", "sabre",
  "sacar", "sacos", "sacou", "safar", "safra", "saiam", "saias", "saiba", "saida", "saido", "saira", "salao",
  "salas", "saldo", "salsa", "salta", "salte", "salto", "salva", "salve", "salvo", "samba", "santa", "santo",
  "sapos", "saque", "sarar", "saude", "sauna", "secao", "secar", "secas", "secos", "secou", "segue", "segui",
  "seios", "seita", "sejam", "sejas", "selar", "selos", "selva", "semen", "senao", "sendo", "senha", "senso",
  "senta", "sente", "senti", "sento", "serao", "seras", "serei", "serem", "seres", "seria", "serie", "serio",
  "serra", "serva", "serve", "servi", "servo", "setor", "sexos", "sexta", "sexto", "sigam", "signo", "silva",
  "sinal", "sinos", "sinta", "sinto", "siria", "sirva", "sirvo", "sitio", "soava", "sobem", "sobra", "sobre",
  "socar", "socia", "socio", "socos", "socou", "sodio", "sofra", "sofre", "sofri", "sofro", "sogra", "sogro",
  "solar", "solta", "solte", "solto", "somar", "somem", "somos", "sonda", "sonha", "sonhe", "sonho", "sopra",
  "sopre", "sopro", "sorri", "sorte", "sotao", "soube", "suada", "suado", "suave", "subam", "subia", "subir",
  "subiu", "sucos", "sudao", "sueca", "sueco", "sugar", "suica", "suico", "sujar", "sujas", "sujos", "sujou",
  "sumam", "sumir", "sumiu", "super", "supoe", "supor", "surda", "surdo", "surge", "surra", "surto", "susto",
  "sutia", "sutil", "sutis", "tabua", "tacas", "tacos", "talao", "talco", "tampa", "tango", "tanta", "tanto",
  "tapas", "tarde", "taxas", "taxis", "tedio", "teias", "telas", "temas", "temem", "temer", "temia", "temor",
  "temos", "tempo", "tenda", "tende", "tendo", "tenha", "tenho", "tenis", "tensa", "tenso", "tenta", "tente",
  "tento", "tenue", "terao", "teras", "terca", "terco", "terei", "terem", "teres", "teria", "termo", "terno",
  "terra", "tesao", "testa", "teste", "tetas", "texto", "tiara", "tigre", "times", "tinha", "tinta", "tinto",
  "tipos", "tiram", "tirar", "tiras", "tirei", "tirem", "tiros", "tirou", "titas", "titia", "tiver", "tocam",
  "tocar", "tocha", "tocou", "todas", "todos", "tolas", "tolos", "tomam", "tomar", "tomas", "tomei", "tomem",
  "tomou", "tonta", "tonto", "topar", "toque", "torax", "torci", "torna", "torne", "torno", "torre", "torta",
  "torto", "tosse", "total", "touro", "trace", "traco", "traga", "trago", "trair", "traiu", "traje", "trama",
  "trapo", "trara", "trata", "trate", "trato", "trava", "trave", "treme", "treno", "trens", "treta", "treze",
  "tribo", "trico", "trigo", "trina", "troca", "troco", "trono", "tropa", "trote", "truta", "tubos", "tumba",
  "tumor", "tunel", "turbo", "turco", "turma", "turne", "turno", "tutor", "ultra", "umida", "umido", "unhas",
  "uniao", "unica", "unico", "unida", "unido", "urina", "ursos", "usada", "usado", "usara", "usava", "usina",
  "usual", "uteis", "utero", "vacas", "vacuo", "vadia", "vadio", "vagao", "vagar", "vagas", "valem", "valer",
  "vales", "valeu", "valha", "valho", "valia", "valor", "valsa", "vamos", "vapor", "varas", "vasos", "vasta",
  "vasto", "vazar", "vazia", "vazio", "vazou", "veado", "veias", "vejam", "velas", "velha", "velho", "veloz",
  "vemos", "venca", "vence", "venci", "venda", "vende", "vendi", "vendo", "venha", "venho", "vento", "verao",
  "verba", "verbo", "verde", "verei", "verem", "veria", "verme", "verso", "vespa", "veste", "vesti", "vetor",
  "vezes", "viaja", "viaje", "viajo", "vicio", "vidas", "video", "vidro", "viena", "vigas", "vigia", "vigie",
  "vigor", "vilao", "vilas", "vimos", "vinda", "vindo", "vinha", "vinho", "vinte", "viola", "viram", "virao",
  "virar", "virei", "virem", "viria", "viril", "virou", "virus", "visao", "visse", "vista", "viste", "visto",
  "vital", "viuva", "viuvo", "vivam", "vivas", "vivem", "viver", "viveu", "vivia", "vivos", "voces", "vodca",
  "volei", "volta", "volte", "volto", "volvo", "vossa", "vosso", "votar", "votei", "votem", "votos", "votou",
  "vozes", "xeque", "zebra", "zeros", "ziper", "zomba", "zonas", "zumbi"
];

export const ALLOWED = [
  "abaco", "abafa", "abafe", "abafo", "abala", "abale", "abalo", "abana", "abane", "abano", "abata", "abati",
  "abato", "abeto", "ablua", "ablui", "abluo", "abole", "aboli", "abono", "abras", "abres", "abreu", "abris",
  "abste", "abusa", "abuse", "acaro", "acata", "acate", "acato", "acena", "aceno", "aceto", "achai", "aches",
  "acida", "acode", "acola", "acuai", "acuam", "acuar", "acuas", "acuda", "acude", "acudi", "acudo", "acuei",
  "acuem", "acues", "acuou", "acuse", "acuso", "adere", "aderi", "adiai", "adiam", "adias", "adida", "adido",
  "adiei", "adiem", "adies", "adimo", "adiou", "adira", "adiro", "adita", "adite", "adito", "adoca", "adoce",
  "adoco", "adota", "adote", "adoto", "aduba", "adube", "adubo", "adula", "adule", "adulo", "advem", "advim",
  "advir", "afaga", "afago", "afana", "afane", "afano", "afega", "afere", "aferi", "afete", "afiai", "afiam",
  "afiar", "afias", "afiei", "afiem", "afies", "afina", "afine", "afino", "afins", "afiou", "afira", "afiro",
  "afixa", "afixe", "afixo", "aflua", "aflui", "afluo", "afoba", "afobe", "afobo", "afofa", "afofe", "afofo",
  "afoga", "afogo", "afore", "aforo", "afros", "aftas", "agape", "agata", "ageis", "agiam", "agias", "agimo",
  "agios", "agira", "agite", "agito", "aguai", "aguam", "aguar", "aguca", "aguce", "aguco", "aguei", "aguem",
  "agues", "aguou", "ajais", "ajamo", "alada", "alado", "alaga", "alago", "alamo", "alcai", "alcam", "alcar",
  "alcas", "alcei", "alcem", "alces", "alcou", "aldea", "alego", "algoz", "alhea", "alhos", "aliai", "aliam",
  "aliar", "aliei", "aliem", "alies", "alija", "alije", "alijo", "aliou", "alisa", "alise", "aliso", "aloca",
  "aloco", "aloes", "aloja", "aloje", "alojo", "altea", "aluda", "alude", "aludi", "aludo", "alugo", "alvas",
  "alves", "alvor", "amago", "amais", "amamo", "amaro", "ameba", "ameca", "ameia", "ameis", "amemo", "amena",
  "ameno", "amido", "amima", "amime", "amimo", "amola", "amole", "amolo", "anais", "ancas", "ancia", "andai",
  "andas", "andes", "andor", "anela", "anele", "anelo", "anexa", "anexe", "anglo", "angra", "anodo", "anota",
  "anoto", "ansia", "antao", "antas", "antro", "anuam", "anuas", "anuem", "anuia", "anuir", "anuis", "anuiu",
  "anula", "anule", "anulo", "apago", "apara", "apare", "aparo", "apeai", "apear", "apeei", "apega", "apego",
  "apeia", "apeie", "apeio", "apela", "apele", "apena", "apene", "apeno", "apeou", "apita", "apite", "apoie",
  "aptas", "aptos", "apura", "apure", "apuro", "aquem", "araca", "arada", "arado", "arais", "aramo", "arara",
  "arava", "arcai", "arcam", "arcas", "arcou", "ardam", "ardas", "ardei", "ardem", "ardes", "ardeu", "ardia",
  "ardil", "ardis", "ardor", "ardua", "areal", "areis", "areja", "areje", "arejo", "aremo", "arfai", "arfam",
  "arfar", "arfas", "arfei", "arfem", "arfes", "arfou", "argua", "argui", "arguo", "arias", "arida", "arido",
  "armai", "armam", "armei", "armem", "armes", "arpoa", "arpoe", "arpoo", "arque", "arrea", "arria", "arrie",
  "arrio", "asila", "asile", "asnos", "assai", "assam", "assas", "assaz", "assea", "assei", "assem", "asses",
  "assis", "assoa", "assoe", "assoo", "assou", "ataco", "atada", "atado", "atais", "atamo", "atara", "atava",
  "ateai", "atear", "ateei", "ateia", "ateie", "ateio", "ateis", "atemo", "atens", "ateou", "atera", "ateus",
  "ateve", "atica", "atice", "atico", "atido", "atina", "atine", "atino", "atola", "atole", "atolo", "atona",
  "atono", "atrio", "atuai", "atuam", "atuas", "atuei", "atuem", "atues", "atuns", "atura", "ature", "aturo",
  "audaz", "auras", "aurea", "aureo", "autos", "autua", "autue", "autuo", "avais", "avara", "avaro", "aveio",
  "avela", "avens", "aviai", "aviam", "aviar", "avias", "avida", "avido", "aviei", "aviem", "avier", "avies",
  "avimo", "aviou", "avira", "aviva", "avive", "avivo", "axial", "axila", "azara", "azare", "azaro", "azeda",
  "azede", "azias", "azimo", "azoto", "azula", "azule", "azulo", "babai", "babam", "babao", "babei", "babem",
  "babes", "babou", "bacos", "bafos", "bagas", "bagos", "bahia", "baiao", "baias", "baila", "bailo", "balam",
  "balea", "balem", "bales", "balia", "balir", "balis", "baliu", "bambo", "banem", "banes", "banhe", "bania",
  "banis", "baniu", "baque", "bardo", "bario", "barre", "basea", "baste", "basto", "batas", "batei", "batel",
  "bauru", "beata", "beato", "bebas", "bebei", "becas", "beico", "beire", "beiro", "bemol", "bento", "benza",
  "benze", "benzi", "benzo", "beque", "berna", "berra", "berre", "berro", "bicai", "bicam", "bicar", "bicas",
  "bicou", "biela", "bigas", "bilis", "bique", "birra", "bisao", "blefa", "blefo", "bobea", "bocal", "bocha",
  "bodes", "boers", "boiai", "boiam", "boiar", "boias", "boiei", "boiem", "boies", "boina", "boiou", "bolai",
  "bolam", "bolao", "boldo", "bolei", "bolem", "boles", "bolou", "bones", "borde", "borra", "borre", "borro",
  "bossa", "botai", "botam", "botem", "boxea", "braba", "brabo", "braca", "brada", "brade", "brado", "braga",
  "brama", "brame", "brami", "bramo", "breca", "breco", "brejo", "breta", "brida", "brigo", "brins", "brios",
  "brita", "brito", "broas", "broco", "bromo", "brota", "brote", "broto", "bruma", "bucal", "bucha", "bucho",
  "bueno", "bufai", "bufam", "bufao", "bufar", "bufas", "bufei", "bufem", "bufes", "bufou", "bujao", "bulam",
  "bulas", "bulbo", "bules", "bulia", "bulir", "bulis", "buliu", "bumbo", "bunde", "bundo", "burgo", "burla",
  "burle", "burlo", "buxos", "buzio", "cabei", "cabes", "cabia", "cacai", "cacao", "cacei", "cacem", "caces",
  "cacho", "cacoa", "cacoe", "cacoo", "cacou", "cacto", "cagai", "cagam", "cagas", "cague", "caiai", "caiar",
  "caias", "caiba", "caibo", "caiei", "caiem", "caies", "caimo", "caiou", "calai", "calam", "calas", "calce",
  "calco", "calei", "cales", "calha", "calhe", "calho", "calos", "calou", "calva", "calvo", "canaa", "canas",
  "canga", "canja", "canse", "capai", "capam", "capar", "capei", "capem", "capes", "capim", "capou", "capta",
  "capte", "capto", "capua", "caput", "carao", "cardo", "carmo", "carpa", "carpe", "carpi", "casai", "casem",
  "cases", "caspa", "cassa", "casse", "casso", "casto", "catai", "catam", "catas", "catei", "catem", "cates",
  "catou", "catre", "caule", "causo", "cauta", "cauto", "cavai", "cavam", "cavas", "cavei", "cavem", "caves",
  "cavia", "cavie", "cavio", "ceado", "ceais", "ceamo", "ceara", "ceava", "cedam", "cedas", "cedei", "cedem",
  "cedes", "cedia", "cedro", "ceeis", "ceemo", "cegai", "cegam", "cegar", "cegou", "cegue", "ceiam", "ceias",
  "ceiem", "ceies", "ceifa", "ceife", "ceifo", "celia", "celta", "censo", "ceras", "cerda", "cerne", "cerni",
  "cerol", "cerra", "cerre", "cerro", "cesio", "cessa", "cesse", "cesso", "cetim", "chaga", "chago", "checo",
  "chefa", "chiai", "chiam", "chiar", "chias", "chica", "chiei", "chiem", "chies", "chiou", "choca", "choco",
  "chova", "chovi", "chovo", "chupo", "chuto", "cidra", "cifra", "cifre", "cifro", "cilio", "cinda", "cinde",
  "cindi", "cindo", "cinge", "cingi", "cinja", "cinjo", "ciosa", "cioso", "cipos", "cirio", "cisao", "cisca",
  "cisma", "cisme", "cismo", "citai", "citam", "citas", "citei", "citem", "cites", "clama", "clame", "clamo",
  "clava", "clero", "clips", "coada", "coado", "coagi", "coais", "coaja", "coajo", "coamo", "coara", "coava",
  "coaxa", "coaxe", "coaxo", "cocai", "cocal", "cocam", "cocas", "cocei", "cocem", "coces", "cocho", "cocou",
  "codea", "coege", "coeis", "coemo", "coesa", "coeso", "coeva", "coevo", "coiba", "coibe", "coibi", "coibo",
  "coice", "coifa", "coito", "colai", "colam", "colas", "colei", "colem", "coles", "colha", "colhe", "colhi",
  "colho", "comas", "comei", "compo", "cones", "conga", "copie", "copio", "corai", "coram", "corar", "coras",
  "corca", "corei", "corem", "corja", "coroe", "coroo", "coros", "corou", "cosam", "cosas", "cosei", "cosem",
  "coser", "coses", "coseu", "cosia", "cotai", "cotam", "cotar", "cotas", "cotei", "cotem", "cotes", "cotou",
  "coube", "couto", "coxim", "coxos", "cozam", "cozas", "cozei", "cozem", "cozer", "cozes", "cozeu", "cozia",
  "crava", "crave", "cravo", "crede", "creem", "crema", "cremo", "crera", "criai", "crido", "criem", "cries",
  "crina", "criva", "crive", "crivo", "croma", "crome", "cromo", "cruas", "cruzo", "cubas", "cucas", "cucos",
  "cuias", "cuica", "cujus", "culta", "cumes", "cunha", "cunhe", "cunho", "cupim", "curai", "curam", "curas",
  "curei", "curem", "cures", "curia", "cursa", "curse", "curti", "curve", "curvo", "cuspi", "cuspo", "cutis",
  "dalia", "danai", "danam", "danas", "danei", "danes", "danou", "daras", "dares", "datai", "datam", "datar",
  "datei", "datem", "dates", "datou", "davas", "decai", "dedal", "deduz", "deito", "demao", "depoe", "depos",
  "depus", "deras", "deres", "dermo", "despe", "despi", "devas", "devei", "deveu", "digne", "dilua", "dilui",
  "diluo", "diodo", "dique", "diras", "disca", "dispo", "dista", "diste", "ditai", "ditam", "ditei", "ditem",
  "dites", "ditos", "ditou", "divas", "dizei", "doada", "doado", "doais", "doamo", "doara", "doava", "doeis",
  "doemo", "doera", "dogma", "doiam", "doias", "domai", "domam", "domas", "domei", "domem", "domes", "domou",
  "donde", "dopai", "dopam", "dopar", "dopas", "dopei", "dopem", "dopes", "dopou", "dorso", "dosai", "dosam",
  "dosar", "dosas", "dosei", "dosem", "dosou", "dotai", "dotam", "dotar", "dotas", "dotei", "dotem", "dotes",
  "dotou", "doura", "doure", "douro", "douta", "douto", "draga", "drago", "drena", "drene", "dreno", "drogo",
  "duais", "dubia", "dubio", "dubla", "duble", "dublo", "duela", "duele", "dumas", "dunga", "durai", "durei",
  "durem", "dures", "dutos", "ebano", "ebrio", "ecoai", "ecoam", "ecoar", "ecoas", "ecoei", "ecoem", "ecoes",
  "ecoou", "edema", "edita", "edite", "edito", "educa", "educo", "eguas", "eiras", "ejeta", "ejete", "ejeto",
  "elege", "elegi", "eleja", "elejo", "eleve", "elevo", "elixa", "elixe", "elixi", "elixo", "elmos", "emana",
  "emane", "emano", "emita", "emiti", "emito", "emula", "emule", "emulo", "encho", "enfio", "enjoa", "enjoe",
  "enjoo", "enoje", "enojo", "entoa", "entoe", "entoo", "ereis", "ereta", "ereto", "ergam", "ergas", "ergue",
  "ergui", "erica", "erice", "erico", "erige", "erigi", "erija", "erijo", "ermos", "eroda", "erode", "erodi",
  "erodo", "errai", "erram", "erras", "errem", "erres", "escoa", "escoe", "escol", "escoo", "esima", "esimo",
  "espie", "espio", "estai", "estio", "esvai", "etano", "eteno", "etilo", "etipe", "etnia", "evada", "evade",
  "evadi", "evado", "evito", "evoca", "evoco", "exala", "exale", "exalo", "exara", "exare", "exaro", "exiba",
  "exibe", "exibi", "exibo", "exigi", "exija", "exila", "exile", "exilo", "exima", "exime", "eximi", "eximo",
  "exodo", "expia", "expie", "expio", "expoe", "expus", "exuma", "exume", "exumo", "facho", "fados", "faina",
  "falai", "falda", "fales", "falhe", "falho", "falia", "falis", "faliu", "falte", "falto", "famas", "faras",
  "faros", "farpa", "farte", "fatie", "fatio", "fatuo", "fauna", "fauno", "favas", "favos", "fazei", "fecal",
  "fedam", "fedas", "fedei", "fedes", "fedeu", "fedia", "fende", "fendi", "fendo", "feraz", "ferem", "feres",
  "feria", "feris", "ferre", "ferva", "ferve", "fervi", "fervo", "fetal", "fetos", "feudo", "fiado", "fiais",
  "fiamo", "fiapo", "fiara", "fiava", "ficai", "fiche", "ficho", "fiemo", "figas", "figos", "filai", "filam",
  "filao", "filar", "filei", "filem", "files", "filia", "filie", "filio", "filmo", "filou", "finca", "finco",
  "finda", "finde", "findo", "finta", "finte", "finto", "firam", "firas", "firmo", "fisco", "fisga", "fisgo",
  "fitai", "fitam", "fitar", "fitei", "fitem", "fites", "fitou", "fixai", "fixam", "fixas", "fixei", "fixem",
  "fixes", "fixos", "fixou", "flavo", "floco", "flori", "fluam", "fluas", "fluem", "fluia", "fluis", "fluiu",
  "focai", "focam", "focos", "focou", "fofas", "foges", "foice", "foles", "folgo", "folia", "fomes", "foras",
  "forco", "fores", "forja", "forje", "forjo", "forme", "formo", "foros", "forra", "forre", "fosca", "fosco",
  "frade", "fraga", "freai", "frear", "freei", "freia", "freie", "freme", "fremi", "freou", "fresa", "frese",
  "freso", "freta", "frete", "freto", "frevo", "frige", "frigi", "frija", "frijo", "frisa", "frise", "friso",
  "frite", "fruam", "fruas", "fruem", "fruia", "fruir", "fruis", "fruiu", "fucai", "fucam", "fucar", "fucas",
  "fucei", "fucem", "fuces", "fucou", "fugas", "fugaz", "fugis", "fujao", "fujas", "fujem", "fujes", "fujia",
  "fujir", "fujis", "fujiu", "fulge", "fulgi", "fumai", "fumam", "fumas", "fumem", "fumes", "funda", "funde",
  "fundi", "funga", "funil", "funis", "furai", "furam", "furao", "furas", "furei", "furem", "fures", "furna",
  "furor", "furta", "furte", "fusco", "fusos", "fuzis", "gabai", "gabam", "gabas", "gabei", "gabem", "gabes",
  "gabou", "gados", "gagas", "gagos", "gajas", "gajos", "galas", "galga", "galgo", "galia", "gamao", "gamos",
  "ganem", "ganes", "gania", "ganir", "ganis", "ganiu", "garbo", "garca", "garfa", "garfe", "garis", "garoa",
  "garoe", "garoo", "gazua", "geada", "geado", "geais", "geamo", "geara", "geava", "geeis", "geemo", "geiam",
  "geias", "geiem", "geies", "gelai", "gelam", "gelar", "gelas", "gelei", "gelem", "geles", "gelos", "gelou",
  "gemam", "gemas", "gemei", "gemem", "gemer", "gemes", "gemeu", "gemia", "gerai", "geram", "geras", "gerei",
  "gerem", "geres", "geria", "geris", "geriu", "germe", "gesta", "gibao", "ginga", "gingo", "girai", "giram",
  "giras", "girei", "girem", "gires", "giria", "giros", "girou", "gleba", "glosa", "glose", "gloso", "godos",
  "goela", "goias", "golas", "golea", "goles", "gomas", "gomes", "gomos", "gonzo", "gorai", "goram", "gorar",
  "goras", "gorei", "gorem", "gores", "gorou", "gozai", "gozam", "gozas", "gozei", "gozem", "gozes", "gozos",
  "gozou", "grafa", "grafe", "grafo", "gravo", "graxo", "grifa", "grife", "grifo", "grila", "grile", "gruda",
  "grude", "grudo", "guiai", "guiam", "guiei", "guiem", "guies", "guisa", "guizo", "gumes", "guria", "guris",
  "hajam", "hajas", "halos", "haras", "haste", "haure", "hauri", "havei", "heras", "herda", "herde", "herdo",
  "hiato", "hiena", "hifen", "himen", "hinos", "honre", "honro", "horda", "horto", "hulha", "humus", "hunos",
  "iates", "ibero", "icada", "icado", "icais", "icamo", "icara", "icava", "iceis", "icemo", "igapo", "ignea",
  "igneo", "ilesa", "ilhai", "ilham", "ilhar", "ilhei", "ilhem", "ilhes", "ilhou", "iluda", "ilude", "iludi",
  "iludo", "imite", "imito", "imola", "imole", "imolo", "impar", "impia", "impio", "impoe", "impos", "impus",
  "inala", "inale", "inalo", "inata", "inato", "incas", "incha", "inche", "incho", "incoa", "incoe", "incoo",
  "induz", "infla", "infle", "inflo", "infra", "iniba", "inibe", "inibi", "inibo", "inova", "inove", "inovo",
  "insta", "inste", "insto", "inter", "intua", "intui", "intuo", "irada", "irdes", "ireis", "iremo", "irias",
  "isola", "isole", "isolo", "istmo", "italo", "itens", "itera", "itere", "itero", "jacas", "jante", "janto",
  "jarda", "jazam", "jazas", "jazei", "jazem", "jazer", "jazes", "jazeu", "jazia", "jecas", "jegue", "jejua",
  "jejue", "jejuo", "jinga", "jogai", "jogas", "jorra", "jorre", "jorro", "jubas", "judie", "judio", "junco",
  "jurai", "juram", "juras", "jurem", "jures", "labia", "labor", "lacai", "lacam", "lacar", "lacas", "lacei",
  "lacem", "laces", "lacio", "lacou", "lacra", "lacre", "lacro", "ladre", "ladro", "lagar", "laica", "laico",
  "lajes", "lamba", "lambi", "lambo", "lanco", "lasca", "lasco", "latao", "latem", "lates", "latia", "latis",
  "latiu", "lauda", "laudo", "lavai", "lavam", "lavas", "lavem", "laves", "lavra", "lavre", "lavro", "ledes",
  "legai", "legam", "legar", "legas", "legou", "legua", "legue", "leias", "leiga", "leigo", "lemas", "lemes",
  "lenga", "lenho", "leoas", "lepra", "leque", "lerao", "leras", "lerda", "lerdo", "lerem", "leres", "leria",
  "lermo", "lesai", "lesam", "lesar", "lesas", "lesei", "lesem", "leses", "lesou", "levai", "levas", "lhama",
  "liame", "lidai", "lidas", "lidem", "lides", "lieis", "ligai", "lilas", "limai", "limam", "limar", "limas",
  "limei", "limem", "limes", "limou", "lince", "linfa", "lirio", "lisas", "lisos", "liste", "listo", "litio",
  "lixai", "lixam", "lixar", "lixas", "lixei", "lixem", "lixes", "lixou", "lobao", "lobas", "locai", "locam",
  "locar", "locas", "locou", "logra", "logre", "logro", "lonas", "lopes", "loque", "lotai", "lotam", "lotar",
  "lotas", "lotea", "lotei", "lotem", "lotou", "lousa", "louva", "louve", "louvo", "lucra", "lucre", "lulas",
  "lupas", "lusas", "lusos", "lutai", "lutes", "luxos", "luzam", "luzas", "luzem", "luzia", "luzir", "luzis",
  "luziu", "macom", "macos", "macro", "magma", "magna", "magno", "magoe", "magoo", "malhe", "malho", "mamai",
  "mamam", "mamao", "mamar", "mamei", "mamem", "mames", "mamou", "manas", "manca", "manea", "manes", "manja",
  "manje", "manjo", "mansa", "manso", "mante", "mapea", "marra", "masca", "masco", "matai", "matas", "mates",
  "matiz", "matos", "meada", "mecam", "mecas", "medem", "medes", "medis", "mediu", "medra", "medre", "medro",
  "meiao", "melai", "melam", "melar", "melas", "melei", "melem", "meles", "melou", "melro", "menea", "menir",
  "menus", "meras", "metam", "metei", "metem", "metes", "metia", "mexas", "mexei", "mexes", "miado", "miais",
  "miamo", "miara", "miava", "micos", "mieis", "miemo", "migra", "migre", "migro", "mijai", "mijam", "mijas",
  "mijei", "mijem", "mijes", "mimai", "mimam", "mimar", "mimas", "mimei", "mimem", "mimes", "mimos", "mimou",
  "minai", "minam", "minar", "minei", "minem", "mines", "minis", "minou", "miolo", "miope", "mirai", "miram",
  "miras", "mirei", "mirem", "mires", "mirou", "mirra", "mista", "misto", "mitra", "mixos", "mixto", "moais",
  "moamo", "mocos", "modas", "modem", "moeis", "moela", "moemo", "moera", "mofai", "mofam", "mofar", "mofas",
  "mofei", "mofem", "mofes", "mofou", "mogem", "moges", "mogno", "mogol", "moiam", "moias", "moida", "moido",
  "moita", "molar", "molas", "molda", "moldo", "molha", "molhe", "momos", "monja", "monto", "morai", "moras",
  "mordi", "morem", "mores", "morsa", "moura", "mouro", "movas", "movei", "moves", "mucos", "mudai", "mudas",
  "mudes", "mudez", "mudos", "mugia", "mugir", "mugis", "mugiu", "mujam", "mujas", "multe", "multi", "multo",
  "munem", "munes", "munia", "munir", "munis", "muniu", "murai", "muram", "murar", "muras", "murei", "murem",
  "mures", "murou", "musas", "musca", "musco", "nabla", "nabos", "nacos", "nadai", "nadam", "nadas", "nadei",
  "nadem", "nades", "nadou", "nafta", "naipe", "nanai", "nanam", "nanar", "nanas", "nanei", "nanem", "nanes",
  "nanou", "nardo", "narra", "narre", "narro", "nasca", "nasco", "natas", "natos", "nauta", "negai", "negam",
  "negas", "nenes", "nesga", "netas", "nevai", "nevam", "nevas", "nevei", "nevem", "neves", "nevou", "nexos",
  "nicho", "ninai", "ninam", "ninas", "ninei", "ninem", "nines", "ninfa", "ninou", "nitro", "nodal", "nodoa",
  "noive", "nomea", "noras", "notai", "notam", "notem", "notes", "nulas", "nulos", "numas", "nunes", "nutra",
  "nutre", "nutri", "nutro", "obesa", "obeso", "obolo", "obsta", "obste", "obsto", "obvie", "ocaso", "ocupe",
  "ocupo", "odiai", "odios", "oitao", "oleos", "olhai", "olhas", "olhes", "oliva", "omita", "omite", "omiti",
  "omito", "oncas", "ondea", "onera", "onere", "onero", "opaca", "opaco", "opala", "opere", "opero", "opina",
  "opine", "opino", "opoem", "opoes", "opomo", "opora", "optai", "optam", "optas", "optei", "optem", "optes",
  "optou", "orado", "orais", "oramo", "orara", "orava", "orcai", "orcam", "orcar", "orcas", "orcei", "orcem",
  "orces", "orcou", "oreis", "oremo", "orfas", "orgem", "orges", "orlai", "orlam", "orlar", "orlas", "orlei",
  "orlem", "orles", "orlou", "ornai", "ornam", "ornar", "ornas", "ornei", "ornem", "ornes", "ornou", "osseo",
  "otico", "oucas", "ouros", "ousai", "ousas", "ousei", "ousem", "ouses", "ouves", "ouvis", "ovais", "ovino",
  "oxida", "oxide", "oxido", "pagai", "pagem", "paira", "paire", "pairo", "pajea", "palmo", "pampa", "panca",
  "papam", "papao", "papar", "papas", "papei", "papem", "papes", "papos", "papou", "parai", "paras", "parca",
  "parco", "parda", "pardo", "parea", "paria", "parir", "parvo", "pasma", "pasme", "pasmo", "paste", "patim",
  "patua", "pauta", "paute", "pauto", "pecai", "pecar", "pecou", "pedes", "pedis", "pegai", "peida", "peide",
  "peita", "peite", "pelai", "pelam", "pelar", "pelei", "pelem", "pelou", "penai", "penam", "penar", "penca",
  "penda", "pende", "pendi", "pendo", "penei", "penem", "penes", "penou", "peque", "peras", "pesai", "pesam",
  "pesas", "pesco", "pesei", "pesem", "peses", "pesou", "petiz", "piado", "piais", "piamo", "piara", "piaui",
  "piava", "picai", "picam", "picao", "picas", "picha", "piche", "picho", "picou", "pieis", "piemo", "pifai",
  "pifam", "pifar", "pifas", "pifei", "pifem", "pifes", "pifou", "pilao", "pilhe", "pilho", "pince", "pinco",
  "pinga", "pinha", "pinho", "pioro", "pipas", "pique", "pirao", "pires", "pisai", "pisam", "pisas", "pisco",
  "pisem", "pises", "pivos", "pixel", "plane", "plato", "plebe", "plota", "plote", "ploto", "pluga", "plugo",
  "pluma", "pocas", "podai", "podam", "podar", "podas", "podei", "podio", "podou", "polca", "polia", "polis",
  "poliu", "polos", "polpa", "pomos", "pompa", "ponca", "ponde", "poras", "pores", "posai", "posam", "posas",
  "posei", "posem", "poses", "posou", "pospo", "poupo", "pousa", "pouse", "povao", "povoa", "povoe", "povoo",
  "praxe", "prelo", "prema", "preme", "premi", "premo", "prepo", "preza", "preze", "prezo", "priva", "prive",
  "privo", "proas", "propo", "prosa", "provi", "provo", "prumo", "pubis", "pudor", "pulai", "pulam", "pulas",
  "pulem", "pules", "pulga", "pulos", "pulsa", "pulse", "pumas", "punam", "punas", "punem", "punes", "punha",
  "punia", "punis", "puniu", "puras", "purga", "purgo", "puxai", "puxam", "puxao", "puxas", "puxes", "quede",
  "quedo", "quepe", "quere", "quica", "quina", "quipa", "quita", "quite", "quito", "quota", "racha", "rache",
  "racho", "radia", "radie", "raiai", "raiam", "raiar", "raias", "raiei", "raiem", "raies", "raiou", "rajai",
  "rajam", "rajar", "rajas", "rajei", "rajem", "rajes", "rajou", "ralai", "ralam", "ralar", "ralas", "ralei",
  "ralem", "rales", "ralha", "ralhe", "ralho", "ralos", "ralou", "ranco", "rangi", "ranja", "ranjo", "rapai",
  "rapam", "rapar", "rapas", "rapei", "rapem", "rapes", "rapou", "rapta", "rapte", "rarea", "rasas", "rasga",
  "rasgo", "rasos", "raspa", "raspe", "raspo", "rasto", "ratas", "ratea", "reagi", "reaja", "reajo", "reata",
  "reate", "reato", "reave", "reboa", "reboe", "reboo", "recai", "recea", "recua", "recuo", "redea", "redil",
  "reege", "refaz", "refez", "refiz", "regai", "regam", "regar", "regas", "regei", "regem", "reger", "reges",
  "regeu", "regia", "regio", "regou", "regre", "regro", "regua", "regue", "reine", "rejam", "rejas", "reler",
  "reles", "releu", "relia", "remai", "remam", "remas", "remei", "remes", "remia", "remir", "remis", "remiu",
  "remoa", "remoe", "remoi", "remoo", "remou", "rendi", "rente", "repoe", "repos", "repus", "reses", "resma",
  "reste", "retas", "retem", "retos", "reuni", "reuno", "reves", "revia", "revir", "reviu", "rezai", "rezam",
  "rezas", "rezem", "rezes", "rezou", "riais", "riamo", "ribas", "rides", "rieis", "rifai", "rifam", "rifar",
  "rifas", "rifei", "rifem", "rifes", "rifou", "rijas", "rijos", "rimai", "rimam", "rimar", "rimei", "rimem",
  "rimes", "rimou", "ripas", "rirao", "riras", "rirei", "rires", "riria", "rirmo", "risca", "risse", "riste",
  "ritos", "rixas", "roais", "roamo", "rocai", "rocam", "rocar", "rocas", "rocei", "rocem", "roces", "rocio",
  "rocou", "rodai", "rodam", "rodea", "rodei", "rodem", "rodes", "rodos", "rodou", "roeis", "roemo", "roera",
  "rogai", "rogam", "rogar", "rogas", "rogem", "roges", "rogos", "rogou", "rogue", "roiam", "roias", "roida",
  "roido", "rojao", "rolai", "rolam", "rolas", "rolei", "rolem", "roles", "romas", "rombo", "rompa", "rompe",
  "rompi", "rompo", "ronde", "rondo", "roque", "rosca", "rosea", "roseo", "rosna", "rosne", "rosno", "rotea",
  "rotos", "rouca", "rouco", "roxas", "roxos", "rubis", "rublo", "rubra", "rubro", "ruela", "rufai", "rufam",
  "rufar", "rufas", "rufei", "rufem", "rufes", "rufou", "rugai", "rugam", "rugar", "rugia", "rugir", "rugis",
  "rugiu", "rugou", "rugue", "ruiam", "ruias", "ruimo", "ruira", "rujam", "rujas", "rumai", "rumam", "rumar",
  "rumas", "rumei", "rumem", "rumes", "rumos", "rumou", "rusga", "sabei", "sacai", "sacam", "sacas", "sacia",
  "sacie", "sacio", "sacis", "sacra", "sacro", "sadia", "sadio", "safai", "safam", "safas", "safei", "safem",
  "safes", "safou", "sagas", "sagaz", "sagra", "sagre", "sagro", "saimo", "salda", "salde", "sales", "salga",
  "salgo", "salmo", "sambe", "sambo", "sanai", "sanam", "sanar", "sanas", "sanea", "sanei", "sanem", "sanes",
  "sanha", "sanou", "sarai", "saram", "saras", "sarca", "sarda", "sarei", "sarem", "sares", "sarna", "sarou",
  "sauda", "saudo", "sauva", "saxao", "seara", "sebes", "sebos", "secai", "secam", "sedas", "sedes", "sedia",
  "sedie", "sedio", "seduz", "seiva", "seixo", "selai", "selam", "selas", "selei", "selem", "seles", "selim",
  "selou", "semea", "senda", "senos", "sepia", "seque", "serre", "serro", "serze", "serzi", "sesta", "setas",
  "sifao", "sigas", "sigla", "sigma", "silex", "silos", "silve", "silvo", "simao", "simio", "sinas", "sirio",
  "siris", "sirza", "sirzo", "sisma", "sisme", "sismo", "sitas", "sitia", "sitie", "sitos", "situa", "situe",
  "situo", "soado", "soais", "soamo", "soara", "sobes", "sobro", "socai", "socam", "socas", "soeis", "soemo",
  "sofas", "solai", "solam", "solas", "solda", "solde", "soldo", "solei", "solem", "soles", "solos", "solou",
  "somai", "somam", "somas", "somei", "somes", "somou", "sonde", "sondo", "sonos", "sonsa", "sonso", "sopas",
  "sopes", "soque", "soros", "sorta", "sorti", "sorva", "sorve", "sorvi", "sorvo", "sosia", "sousa", "souza",
  "sovai", "sovam", "sovar", "sovas", "sovei", "sovem", "soves", "sovou", "suais", "suamo", "suara", "suava",
  "subas", "subis", "sueis", "suemo", "sugai", "sugam", "sugas", "sugou", "sugue", "suina", "suino", "sujai",
  "sujam", "sujei", "sujem", "sujes", "sulca", "sulco", "sulfa", "sumas", "sumia", "sumis", "sunga", "supos",
  "supra", "supre", "supri", "supro", "supus", "surgi", "surja", "surjo", "surre", "surro", "surta", "surte",
  "susta", "suste", "susti", "tabas", "tacai", "tacam", "tacar", "tacha", "tache", "tacho", "tacou", "taipa",
  "talas", "talha", "talhe", "talho", "talos", "tampe", "tampo", "tanga", "tange", "tangi", "tanja", "tanjo",
  "tapai", "tapam", "tapao", "tapar", "tapea", "tapei", "tapem", "tapes", "tapou", "taque", "taras", "tarda",
  "tardo", "tarja", "tatea", "tatua", "tatue", "tatuo", "tatus", "taxai", "taxam", "taxar", "taxei", "taxem",
  "taxes", "taxou", "tecam", "tecas", "tecei", "tecem", "tecer", "teces", "teceu", "tecia", "tecla", "tecle",
  "teclo", "teima", "teime", "teimo", "telao", "teles", "telha", "temam", "temei", "temes", "temeu", "tenaz",
  "tendi", "tenor", "tenra", "tenro", "terna", "tesas", "teses", "tesos", "testo", "tetos", "tibia", "tibio",
  "ticao", "tidas", "tidos", "tiete", "timao", "tinam", "tinas", "tinem", "tines", "tinge", "tingi", "tinia",
  "tinir", "tinis", "tiniu", "tinja", "tinjo", "tirai", "tires", "titio", "toada", "tocai", "tocas", "togas",
  "toldo", "tolha", "tolhe", "tolhi", "tolho", "tomai", "tomba", "tombe", "tombo", "tomes", "tonel", "topai",
  "topam", "topas", "topei", "topem", "topes", "topos", "topou", "toras", "torca", "torce", "torco", "torio",
  "toros", "torpe", "torra", "torro", "tosai", "tosam", "tosar", "tosas", "tosca", "tosco", "tosei", "tosem",
  "toses", "tosou", "tossi", "tosta", "toste", "tosto", "totem", "touca", "traca", "traem", "traia", "traio",
  "trais", "traja", "trajo", "travo", "traze", "treco", "trema", "tremi", "tremo", "trena", "trepa", "trepe",
  "trepo", "treva", "trevo", "trino", "trios", "tripa", "troce", "troia", "trota", "troto", "trova", "truco",
  "trufa", "tufao", "tupis", "turba", "turbe", "turca", "turva", "turve", "turvo", "tussa", "tusso", "ufana",
  "ufane", "ufano", "uivai", "uivam", "uivar", "uivas", "uivei", "uivem", "uives", "uivos", "uivou", "ulula",
  "ulule", "ululo", "unais", "uncao", "unemo", "ungem", "unges", "ungia", "ungir", "ungis", "ungiu", "uniam",
  "unias", "unimo", "unira", "untai", "untam", "untar", "untas", "untei", "untem", "untes", "untou", "urano",
  "urdam", "urdas", "urdem", "urdes", "urdia", "urdir", "urdis", "urdiu", "ureia", "urgia", "urgir", "urgis",
  "urgiu", "urico", "urine", "urino", "urjam", "urjas", "urnas", "urrai", "urram", "urrar", "urras", "urrei",
  "urrem", "urres", "urros", "urrou", "ursas", "urubu", "usais", "usamo", "useis", "usemo", "usura", "vadea",
  "vades", "vadie", "vagai", "vagam", "vagem", "vagia", "vagir", "vagis", "vagiu", "vagos", "vagou", "vague",
  "vaiai", "vaiam", "vaiar", "vaias", "vaiei", "vaiem", "vaies", "vaiou", "valas", "valei", "valos", "varai",
  "varam", "varao", "varar", "varei", "varem", "vares", "varia", "varie", "vario", "varou", "varra", "varre",
  "varri", "varro", "vazai", "vazam", "vazao", "vazas", "vazei", "vazem", "vazes", "vedai", "vedam", "vedar",
  "vedas", "vedei", "vedem", "vedes", "vedou", "vejai", "vejas", "velai", "velam", "velar", "velei", "velem",
  "veles", "velou", "venal", "venco", "venia", "venta", "vente", "veras", "veres", "verga", "versa", "verse",
  "verta", "verte", "verti", "verto", "vesga", "vesgo", "vetai", "vetam", "vetar", "vetas", "vetei", "vetem",
  "vetes", "vetou", "vexai", "vexam", "vexar", "vexas", "vexei", "vexem", "vexes", "vexou", "viana", "vibra",
  "vibre", "vibro", "vicia", "vicie", "vidra", "vidre", "vieis", "viela", "viera", "vieza", "vigio", "vinca",
  "vinco", "vinde", "vinga", "vingo", "vioes", "viole", "violo", "virai", "viras", "vires", "viris", "virmo",
  "visai", "visam", "visar", "visas", "visei", "visem", "vises", "visou", "viuve", "vivaz", "vivei", "vives",
  "voado", "voais", "voamo", "voara", "voava", "voeis", "voemo", "vogal", "volva", "volve", "volvi", "voraz",
  "votai", "votam", "votas", "votes", "vovos", "vulgo", "vulto", "vulva", "xales", "xaras", "xelim", "xerox",
  "xiita", "xinga", "xingo", "xisto", "xucra", "xucro", "zagas", "zanga", "zango", "zanza", "zanze", "zanzo",
  "zarpa", "zarpe", "zarpo", "zelai", "zelam", "zelar", "zelas", "zelei", "zelem", "zeles", "zelou", "zerai",
  "zeram", "zerar", "zeras", "zerei", "zerem", "zeres", "zerou", "zinco", "zombe", "zombo", "zonza", "zonzo",
  "zumba", "zumbe", "zumbo", "zunam", "zunas", "zunem", "zunes", "zunia", "zunir", "zunis", "zuniu", "zurra",
  "zurre", "zurro"
];

/** key -> accented spelling. Keys absent here are already spelled correctly. */
export const DISPLAY = {
  abaco: "ábaco",
  abste: "abstê",
  acaro: "ácaro",
  acida: "ácida",
  acido: "ácido",
  acoes: "ações",
  acola: "acolá",
  acude: "açude",
  adoca: "adoça",
  adoco: "adoço",
  advem: "advém",
  aerea: "aérea",
  aereo: "aéreo",
  afega: "afegã",
  agape: "ágape",
  agata: "ágata",
  ageis: "ágeis",
  agios: "ágios",
  agira: "agirá",
  aguas: "águas",
  aguca: "aguça",
  aguco: "aguço",
  aguia: "águia",
  alamo: "álamo",
  album: "álbum",
  alcai: "alçai",
  alcam: "alçam",
  alcar: "alçar",
  alcas: "alças",
  alcou: "alçou",
  aldea: "aldeã",
  alema: "alemã",
  alhea: "alheá",
  alias: "aliás",
  alibi: "álibi",
  aloes: "aloés",
  altea: "alteá",
  amago: "âmago",
  amara: "amará",
  ambar: "âmbar",
  ameca: "ameça",
  ancia: "anciã",
  andre: "andré",
  aneis: "anéis",
  animo: "ânimo",
  anodo: "ânodo",
  anoes: "anões",
  ansia: "ânsia",
  antao: "antão",
  anuia: "anuía",
  apice: "ápice",
  apoie: "apóie",
  aquem: "aquém",
  arabe: "árabe",
  araca: "araçá",
  ardua: "árdua",
  arduo: "árduo",
  areas: "áreas",
  arias: "árias",
  arida: "árida",
  arido: "árido",
  arpao: "arpão",
  arrea: "arreá",
  assea: "asseá",
  atens: "aténs",
  atera: "aterá",
  atica: "atiça",
  atico: "atiço",
  atomo: "átomo",
  atona: "átona",
  atono: "átono",
  atras: "atrás",
  atrio: "átrio",
  aurea: "áurea",
  aureo: "áureo",
  avela: "avelã",
  avens: "avéns",
  aviao: "avião",
  avida: "ávida",
  avido: "ávido",
  avira: "avirá",
  azimo: "ázimo",
  babao: "babão",
  babas: "babás",
  bacos: "baços",
  baiao: "baião",
  balao: "balão",
  balea: "baleá",
  barao: "barão",
  bario: "bário",
  basea: "baseá",
  bebes: "bebês",
  beico: "beiço",
  berco: "berço",
  bilis: "bílis",
  bisao: "bisão",
  bobea: "bobeá",
  boers: "bôers",
  boiem: "bóiem",
  boies: "bóies",
  bolao: "bolão",
  bones: "bonés",
  bonus: "bônus",
  botao: "botão",
  boxea: "boxeá",
  braca: "braça",
  braco: "braço",
  breta: "bretã",
  bufao: "bufão",
  bujao: "bujão",
  buzio: "búzio",
  cacai: "caçai",
  cacam: "caçam",
  cacao: "cação",
  cacar: "caçar",
  cacas: "caças",
  cacoa: "caçoa",
  cacoe: "caçoe",
  cacoo: "caçoo",
  cacou: "caçou",
  cafes: "cafés",
  caida: "caída",
  caido: "caído",
  caimo: "caímo",
  caira: "cairá",
  calca: "calça",
  calco: "calço",
  canaa: "canaã",
  capua: "cápua",
  carao: "carão",
  celia: "célia",
  cesar: "césar",
  cesio: "césio",
  chale: "chalé",
  cilio: "cílio",
  cipos: "cipós",
  cirio: "círio",
  cisao: "cisão",
  ciume: "ciúme",
  cocai: "coçai",
  cocam: "coçam",
  cocar: "coçar",
  cocas: "coças",
  cocou: "coçou",
  codea: "côdea",
  coiba: "coíba",
  coibe: "coíbe",
  coibo: "coíbo",
  colon: "cólon",
  compo: "compô",
  conga: "congá",
  copia: "cópia",
  corca: "corça",
  cuica: "cuíca",
  curia: "cúria",
  cutis: "cútis",
  dalia: "dália",
  danca: "dança",
  danco: "danço",
  darao: "darão",
  daras: "darás",
  debil: "débil",
  dedao: "dedão",
  demao: "demão",
  depoe: "depõe",
  depos: "depôs",
  desca: "desça",
  desco: "desço",
  detem: "detém",
  dirao: "dirão",
  diras: "dirás",
  dispo: "dispô",
  doiam: "doíam",
  doias: "doías",
  dolar: "dólar",
  dubia: "dúbia",
  dubio: "dúbio",
  duzia: "dúzia",
  ebano: "ébano",
  ebrio: "ébrio",
  eguas: "éguas",
  entao: "então",
  epica: "épica",
  epico: "épico",
  epoca: "época",
  ereis: "éreis",
  erica: "eriça",
  erico: "eriço",
  erige: "eríge",
  esima: "ésima",
  esimo: "ésimo",
  espia: "espiã",
  estao: "estão",
  etica: "ética",
  etico: "ético",
  etipe: "etípe",
  exito: "êxito",
  exodo: "êxodo",
  expoe: "expõe",
  expos: "expôs",
  facam: "façam",
  facao: "facão",
  facil: "fácil",
  farao: "farão",
  faras: "farás",
  fatuo: "fátuo",
  felix: "félix",
  femea: "fêmea",
  femur: "fêmur",
  fieis: "fiéis",
  filao: "filão",
  fluia: "fluía",
  fogao: "fogão",
  forca: "força",
  forco: "forço",
  forum: "fórum",
  frige: "fríge",
  fruia: "fruía",
  fucai: "fuçai",
  fucam: "fuçam",
  fucar: "fuçar",
  fucas: "fuças",
  fucou: "fuçou",
  fujao: "fujão",
  furao: "furão",
  furia: "fúria",
  fusao: "fusão",
  futil: "fútil",
  galao: "galão",
  galia: "gália",
  gamao: "gamão",
  gamba: "gambá",
  garca: "garça",
  gemea: "gêmea",
  gemeo: "gêmeo",
  genio: "gênio",
  gibao: "gibão",
  giria: "gíria",
  godos: "gôdos",
  goias: "goiás",
  golea: "goleá",
  graca: "graça",
  graos: "grãos",
  habil: "hábil",
  harem: "harém",
  helio: "hélio",
  heroi: "herói",
  hifen: "hífen",
  himen: "hímen",
  humus: "húmus",
  iamos: "íamos",
  icada: "içada",
  icado: "içado",
  icais: "içais",
  icamo: "içamo",
  icara: "içara",
  icava: "içava",
  icone: "ícone",
  idolo: "ídolo",
  igapo: "igapó",
  ignea: "ígnea",
  igneo: "ígneo",
  impar: "ímpar",
  impia: "ímpia",
  impio: "ímpio",
  impoe: "impõe",
  impos: "impôs",
  india: "índia",
  indio: "índio",
  inves: "invés",
  irmao: "irmão",
  irmas: "irmãs",
  italo: "ítalo",
  itens: "ítens",
  japao: "japão",
  juiza: "juíza",
  juizo: "juízo",
  labia: "lábia",
  labio: "lábio",
  lacai: "laçai",
  lacam: "laçam",
  lacar: "laçar",
  lacas: "laças",
  lacio: "lácio",
  lacos: "laços",
  lacou: "laçou",
  lanca: "lança",
  lanco: "lanço",
  lapis: "lápis",
  latao: "latão",
  latex: "látex",
  legua: "légua",
  lenco: "lenço",
  leoes: "leões",
  lerao: "lerão",
  lesao: "lesão",
  licao: "lição",
  lider: "líder",
  lieis: "líeis",
  lilas: "lilás",
  limao: "limão",
  lirio: "lírio",
  litio: "lítio",
  lixao: "lixão",
  lobao: "lobão",
  locao: "loção",
  lotea: "loteá",
  lotus: "lótus",
  macas: "maçãs",
  macom: "maçom",
  macos: "maços",
  mafia: "máfia",
  mamae: "mamãe",
  mamao: "mamão",
  manea: "maneá",
  manes: "manés",
  manha: "manhã",
  mante: "mantê",
  mapea: "mapeá",
  mario: "mário",
  mecam: "meçam",
  mecas: "meças",
  media: "média",
  medio: "médio",
  meiao: "meião",
  melao: "melão",
  menea: "meneá",
  merce: "mercê",
  midia: "mídia",
  miope: "míope",
  miuda: "miúda",
  miudo: "miúdo",
  mocao: "moção",
  mocas: "moças",
  mocos: "moços",
  moiam: "moíam",
  moias: "moías",
  moida: "moída",
  moido: "moído",
  movel: "móvel",
  mumia: "múmia",
  mutua: "mútua",
  mutuo: "mútuo",
  nacao: "nação",
  nasca: "nasça",
  nasco: "nasço",
  negao: "negão",
  nenem: "neném",
  nenes: "nenês",
  nevoa: "névoa",
  nivel: "nível",
  nocao: "noção",
  nodoa: "nódoa",
  nomea: "nomeá",
  oasis: "oásis",
  obito: "óbito",
  obolo: "óbolo",
  obtem: "obtém",
  obvia: "óbvia",
  obvio: "óbvio",
  odios: "ódios",
  oitao: "oitão",
  oleos: "óleos",
  oncas: "onças",
  ondea: "ondeá",
  opcao: "opção",
  opera: "ópera",
  opoem: "opõem",
  opoes: "opões",
  opora: "oporá",
  orcai: "orçai",
  orcam: "orçam",
  orcar: "orçar",
  orcou: "orçou",
  orfao: "órfão",
  orfas: "órfãs",
  orgao: "órgão",
  ossea: "óssea",
  osseo: "ósseo",
  otica: "ótica",
  otico: "ótico",
  otima: "ótima",
  otimo: "ótimo",
  oucam: "ouçam",
  oucas: "ouças",
  ovulo: "óvulo",
  oxala: "oxalá",
  oxido: "óxido",
  pagao: "pagão",
  pajea: "pajeá",
  panca: "pança",
  papao: "papão",
  parea: "pareá",
  pareo: "páreo",
  patio: "pátio",
  patua: "patuá",
  pavao: "pavão",
  pecam: "peçam",
  pecas: "peças",
  penis: "pênis",
  peoes: "peões",
  piaui: "piauí",
  picao: "picão",
  pilao: "pilão",
  pinca: "pinça",
  pinco: "pinço",
  pirao: "pirão",
  pivos: "pivôs",
  plato: "platô",
  pocao: "poção",
  pocas: "poças",
  pocos: "poços",
  podio: "pódio",
  polos: "pólos",
  ponca: "poncã",
  ponei: "pônei",
  porao: "porão",
  poras: "porás",
  porem: "porém",
  pospo: "pospô",
  povao: "povão",
  praca: "praça",
  preco: "preço",
  prepo: "prepô",
  preve: "prevê",
  propo: "propô",
  pubis: "púbis",
  puxao: "puxão",
  quere: "querê",
  quica: "quiçá",
  quipa: "quipá",
  racao: "ração",
  racas: "raças",
  radio: "rádio",
  ranco: "ranço",
  rarea: "rareá",
  ratea: "rateá",
  razao: "razão",
  reave: "reavê",
  recea: "receá",
  recem: "recém",
  redea: "rédea",
  refem: "refém",
  regio: "régio",
  regua: "régua",
  remoi: "remoí",
  repoe: "repõe",
  repos: "repôs",
  retem: "retém",
  reuna: "reúna",
  reune: "reúne",
  reuno: "reúno",
  reves: "revés",
  rieis: "ríeis",
  rirao: "rirão",
  robos: "robôs",
  rocai: "roçai",
  rocam: "roçam",
  rocar: "roçar",
  rocio: "rócio",
  rocou: "roçou",
  rodea: "rodeá",
  roiam: "roíam",
  roias: "roías",
  roida: "roída",
  roido: "roído",
  rojao: "rojão",
  romas: "romãs",
  rosea: "rósea",
  roseo: "róseo",
  rotea: "roteá",
  ruido: "ruído",
  ruina: "ruína",
  sabao: "sabão",
  sabio: "sábio",
  saida: "saída",
  saido: "saído",
  saimo: "saímo",
  saira: "sairá",
  salao: "salão",
  sanea: "saneá",
  sarca: "sarça",
  sauda: "saúda",
  saude: "saúde",
  saudo: "saúdo",
  sauva: "saúva",
  saxao: "saxão",
  secao: "seção",
  semea: "semeá",
  semen: "sêmen",
  senao: "senão",
  sepia: "sépia",
  serao: "serão",
  seras: "serás",
  serie: "série",
  serio: "sério",
  sifao: "sifão",
  silex: "sílex",
  simao: "simão",
  simio: "símio",
  siria: "síria",
  sirio: "sírio",
  sitio: "sítio",
  soara: "soará",
  socia: "sócia",
  socio: "sócio",
  sodio: "sódio",
  sofas: "sofás",
  sopes: "sopés",
  sosia: "sósia",
  sotao: "sótão",
  sudao: "sudão",
  suica: "suíça",
  suico: "suíço",
  suina: "suína",
  suino: "suíno",
  supoe: "supõe",
  supos: "supôs",
  sutia: "sutiã",
  tabua: "tábua",
  tacas: "taças",
  talao: "talão",
  tapao: "tapão",
  tapea: "tapeá",
  tatea: "tateá",
  taxis: "táxis",
  tecam: "teçam",
  tecas: "teças",
  tedio: "tédio",
  telao: "telão",
  tenis: "tênis",
  tenue: "tênue",
  terao: "terão",
  teras: "terás",
  terca: "terça",
  terco: "terço",
  tesao: "tesão",
  tibia: "tíbia",
  tibio: "tíbio",
  ticao: "tição",
  tiete: "tietê",
  timao: "timão",
  tinge: "tínge",
  titas: "titãs",
  torax: "tórax",
  torca: "torça",
  torco: "torço",
  torio: "tório",
  traca: "traça",
  traco: "traço",
  trara: "trará",
  treno: "trenó",
  trico: "tricô",
  tufao: "tufão",
  tunel: "túnel",
  turne: "turnê",
  umida: "úmida",
  umido: "úmido",
  uncao: "unção",
  uniao: "união",
  unica: "única",
  unico: "único",
  unira: "unirá",
  urico: "úrico",
  usara: "usará",
  uteis: "úteis",
  utero: "útero",
  vacuo: "vácuo",
  vadea: "vadeá",
  vagao: "vagão",
  varao: "varão",
  vazao: "vazão",
  venca: "vença",
  venco: "venço",
  venia: "vênia",
  verao: "verão",
  veras: "verás",
  vicio: "vício",
  video: "vídeo",
  vieis: "víeis",
  vilao: "vilão",
  vioes: "viões",
  virao: "virão",
  virus: "vírus",
  visao: "visão",
  viuva: "viúva",
  viuvo: "viúvo",
  voara: "voará",
  voces: "vocês",
  volei: "vôlei",
  vovos: "vovós",
  xaras: "xarás",
  ziper: "zíper"
};

export const VALID = new Set([...ANSWERS, ...ALLOWED]);
export const VALID_LIST = [...ANSWERS, ...ALLOWED];
